//DELETE http://localhost:3001/api/blogs/SOMEID

//GET http://localhost:3001/api/blogs
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "New blogpost #3",
    "Author": "Lorenzo Mischaulakia",
    "url": "Tekstiä hienosta tekstistä",
    "likes": 56
}