POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxNzZmZWRmZTM1NzUwNjYzZWRkZGNhZiIsImlhdCI6MTYzNTIzMTk5MX0.m4O8vENY7nLj1aWKqb_LETqH_9pp2yuZr1qibXnCPhw

{
    "author":"test 26.10.2021",
    "title":"test",
    "url":"test",
    "likes":5
}