POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"Blog title 2",
    "author":"Harry Potter",
    "url":"www.google.com",
    "likes":0,
    "userId":"6176ce94ee9531319fe68a9a"
}